### ISSUE TITLE
New to Github: Cant find the function hooke.m

### ISSUE THREAD

**Issue by venugovh** [CALFEM/calfem-matlab-iga#21]
I am not able to find the Matlab function hooke.m for the elasticity tensor.
Sorry, if this is not the right place to post a question.
Could some please help me?

**Comment by yang806** [comment]
> I am not able to find the Matlab function hooke.m for the elasticity tensor.
> Sorry, if this is not the right place to post a question.
> Could some please help me?

hooke.m is in the folder of \calfem-matlab-master\fe. You should see the note in the README.md that "Make sure you have CALFEM for MATLAB installed, see https://github.com/CALFEM/calfem-matlab", install the calfem-matlab, then you can find the hooke.m.
